version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.scribejava:scribejava-core
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: com.okta.sdk:okta-sdk-httpclient
    versions:
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.1.0
